ljdt_app_home:
    path:      /
    defaults:  { _controller: LJDTAppBundle:App:index }

ljdt_admin_home:
    path:      /admin
    defaults:  { _controller: LJDTAppBundle:Admin:index }

ljdt_admin_products:
    path:      /admin/products
    defaults:  { _controller: LJDTAppBundle:Admin:products }

ljdt_admin_product_add:
    path:      /admin/product/add
    defaults:  { _controller: LJDTAppBundle:Admin:addProduct }

ljdt_admin_profiles:
    path:      /admin/profiles
    defaults:  { _controller: LJDTAppBundle:Admin:profiles }

ljdt_admin_profile_add:
    path:      /admin/profile/add
    defaults:  { _controller: LJDTAppBundle:Admin:addProfile }

ljdt_admin_gallery:
    path:      /admin/gallery
    defaults:  { _controller: LJDTAppBundle:Admin:gallery }

ljdt_admin_gallery_add:
    path: /admin/gallery/add
    defaults:  { _controller: LJDTAppBundle:Admin:addGallery }

ljdt_admin_delete:
    path:      /admin/delete/{id}/{section}
    defaults:  { _controller: LJDTAppBundle:Admin:delete }
    requirements:
        id: \d+
